"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Check, ChevronDown, CircleHelp, Clock3, CreditCard, Globe2, Headphones, Menu, Minus, PackageCheck, Plus, Search, ShieldCheck, ShoppingBag, Smartphone, Sparkles, Star, Trash2, Truck, UserRound, Wifi, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Product = { id:number; country:string; flag:string; region:string; operator:string; type:"eSIM"|"SIM"; data:string; days:number; price:number; oldPrice?:number; calls?:string; popular?:boolean; tone:string };

const products: Product[] = [
  { id:1, country:"Турция", flag:"🇹🇷", region:"Европа", operator:"Turkcell", type:"eSIM", data:"20 ГБ", days:30, price:2490, oldPrice:2890, popular:true, tone:"from-[#1679f2] to-[#0d46ad]" },
  { id:2, country:"Таиланд", flag:"🇹🇭", region:"Азия", operator:"AIS", type:"eSIM", data:"Безлимит", days:15, price:3190, calls:"15 минут", tone:"from-[#7047eb] to-[#4020a7]" },
  { id:3, country:"ОАЭ", flag:"🇦🇪", region:"Ближний Восток", operator:"du", type:"SIM", data:"10 ГБ", days:28, price:3590, calls:"30 минут", tone:"from-[#ef6a39] to-[#bb2c21]" },
  { id:4, country:"Германия", flag:"🇩🇪", region:"Европа", operator:"O2", type:"eSIM", data:"30 ГБ", days:30, price:2790, popular:true, tone:"from-[#10a985] to-[#08705c]" },
  { id:5, country:"США", flag:"🇺🇸", region:"Америка", operator:"T-Mobile", type:"eSIM", data:"20 ГБ", days:30, price:3990, calls:"Безлимит", tone:"from-[#ef3f92] to-[#a20d5d]" },
  { id:6, country:"Япония", flag:"🇯🇵", region:"Азия", operator:"KDDI", type:"SIM", data:"15 ГБ", days:16, price:2890, tone:"from-[#27344a] to-[#111827]" },
];
const regions = ["Все направления", "Европа", "Азия", "Ближний Восток", "Америка"];

export default function Storefront() {
  const [query,setQuery]=useState(""); const [region,setRegion]=useState("Все направления"); const [type,setType]=useState("Все типы");
  const [cart,setCart]=useState<Record<number,number>>({}); const [checkout,setCheckout]=useState(false); const [ordered,setOrdered]=useState(false); const [mobileMenu,setMobileMenu]=useState(false);
  const visible=useMemo(()=>products.filter(p=>`${p.country} ${p.operator} ${p.region}`.toLowerCase().includes(query.toLowerCase())&&(region==="Все направления"||p.region===region)&&(type==="Все типы"||p.type===type)),[query,region,type]);
  const cartItems=products.filter(p=>cart[p.id]); const cartCount=Object.values(cart).reduce((s,n)=>s+n,0); const total=cartItems.reduce((s,p)=>s+p.price*cart[p.id],0);
  const add=(id:number)=>setCart(c=>({...c,[id]:(c[id]||0)+1}));
  const change=(id:number,amount:number)=>setCart(c=>{const next=Math.max(0,(c[id]||0)+amount);const updated={...c,[id]:next};if(!next)delete updated[id];return updated});

  useEffect(()=>{
    const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;
    if(!context?.registerTool)return;
    const lifecycle=new AbortController();
    void Promise.resolve(context.registerTool({
      name:"add_tariff_to_cart", title:"Добавить тариф в корзину",
      description:"Добавляет один выбранный тариф SIMKA в корзину по его числовому идентификатору.",
      inputSchema:{type:"object",properties:{productId:{type:"integer",minimum:1,maximum:6}},required:["productId"],additionalProperties:false},
      annotations:{readOnlyHint:false,untrustedContentHint:false},
      execute(input:unknown){const id=(input as {productId?:unknown})?.productId;if(typeof id!=="number"||!products.some(p=>p.id===id))throw new Error("Неизвестный тариф");add(id);return {productId:id,status:"added"};}
    },{signal:lifecycle.signal})).catch(()=>{});
    return ()=>lifecycle.abort();
  },[]);

  return <main className="min-h-screen bg-background text-foreground">
    <div className="border-b border-[#dce7f4] bg-[#edf7ff] px-4 py-2 text-center text-[13px] font-medium text-[#164475]"><span className="inline-flex items-center gap-2"><Sparkles className="size-3.5 text-[#1679f2]"/>Мгновенная доставка eSIM на email · Поддержка 7 дней в неделю</span></div>
    <header className="sticky top-0 z-40 border-b border-border/80 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-[1240px] items-center gap-8 px-4 sm:px-6">
      <a href="#top" className="flex shrink-0 items-center gap-2.5" aria-label="SIMKA — на главную"><Logo/><span className="text-[21px] font-black tracking-[-0.04em] text-[#10213a]">SIMKA</span></a>
      <nav className="hidden items-center gap-7 text-[14px] font-semibold text-[#42526a] lg:flex"><a className="hover:text-[#1168e8]" href="#catalog">Каталог</a><a className="hover:text-[#1168e8]" href="#how">Как это работает</a><a className="hover:text-[#1168e8]" href="#delivery">Доставка</a><a className="hover:text-[#1168e8]" href="#faq">FAQ</a></nav>
      <div className="ml-auto hidden items-center gap-2 md:flex"><Button variant="ghost" className="h-10 rounded-xl text-[#42526a]"><Headphones className="size-4"/>Помощь</Button><Button variant="ghost" className="h-10 rounded-xl text-[#42526a]"><UserRound className="size-4"/>Войти</Button></div>
      <Cart cart={cart} items={cartItems} count={cartCount} total={total} checkout={checkout} ordered={ordered} onChange={change} onCheckout={setCheckout} onOrder={setOrdered}/>
      <button onClick={()=>setMobileMenu(!mobileMenu)} className="grid size-10 place-items-center rounded-xl border lg:hidden" aria-label="Открыть меню">{mobileMenu?<X className="size-5"/>:<Menu className="size-5"/>}</button>
    </div>{mobileMenu&&<nav className="grid gap-1 border-t bg-white p-4 text-sm font-semibold lg:hidden">{[["Каталог","#catalog"],["Как это работает","#how"],["Доставка","#delivery"],["FAQ","#faq"]].map(([label,href])=><a key={href} onClick={()=>setMobileMenu(false)} className="rounded-lg px-3 py-3 hover:bg-muted" href={href}>{label}</a>)}</nav>}</header>

    <section id="top" className="relative overflow-hidden border-b border-[#dce7f4] bg-[#f7fbff]"><div className="absolute inset-0 sim-grid opacity-45"/><div className="relative mx-auto grid max-w-[1240px] items-center gap-8 px-4 py-12 sm:px-6 md:grid-cols-[1.1fr_.9fr] md:py-16"><div>
      <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#cfe1f5] bg-white px-3 py-1.5 text-xs font-bold text-[#28577f]"><Globe2 className="size-3.5 text-[#1168e8]"/>Связь в 120+ странах</div>
      <h1 className="max-w-[720px] text-[clamp(38px,5.2vw,68px)] font-black leading-[.98] tracking-[-0.055em] text-[#10213a]">Интернет в поездке<br/><span className="text-[#1168e8]">без роуминга</span></h1>
      <p className="mt-5 max-w-[570px] text-base leading-7 text-[#56667c] sm:text-lg">Выберите страну, установите eSIM за пару минут или закажите физическую SIM с доставкой.</p>
      <div className="mt-7 flex max-w-[680px] flex-col gap-3 rounded-2xl border border-[#cbdced] bg-white p-2.5 shadow-[0_16px_50px_rgba(29,72,121,.12)] sm:flex-row"><SearchBox value={query} onChange={setQuery}/><Button onClick={()=>document.querySelector("#catalog")?.scrollIntoView({behavior:"smooth"})} className="h-12 rounded-xl bg-[#1168e8] px-7 text-base font-bold hover:bg-[#0d56c3]">Найти тариф<ArrowRight className="size-4"/></Button></div>
      <div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 text-[13px] font-medium text-[#51647a]">{["Без скрытых платежей","Активация за 2 минуты","Поддержка на русском"].map(t=><span key={t} className="flex items-center gap-1.5"><Check className="size-4 text-[#68a71a]"/>{t}</span>)}</div>
    </div><HeroCards/></div></section>

    <section id="catalog" className="mx-auto max-w-[1240px] px-4 py-14 sm:px-6 sm:py-20"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-black uppercase tracking-[.16em] text-[#1168e8]">Популярные направления</p><h2 className="text-3xl font-black tracking-[-.035em] text-[#10213a] sm:text-4xl">Выберите свой тариф</h2></div><p className="max-w-[390px] text-sm leading-6 text-[#637389]">Актуальные предложения проверенных операторов. Цена фиксируется при создании заказа.</p></div>
      <div className="mt-8 flex flex-col gap-3 rounded-2xl border border-[#dbe5ef] bg-[#f8fbfe] p-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-[#7890a8]"/><Input value={query} onChange={e=>setQuery(e.target.value)} className="h-11 rounded-xl border-[#dbe5ef] bg-white pl-10 shadow-none" placeholder="Страна или оператор"/></div><Filter value={region} onChange={setRegion} values={regions}/><Filter value={type} onChange={setType} values={["Все типы","eSIM","SIM"]} narrow/></div>
      {visible.length?<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.map(p=><ProductCard key={p.id} product={p} count={cart[p.id]||0} onAdd={()=>add(p.id)}/>)}</div>:<div className="mt-6 rounded-2xl border border-dashed py-16 text-center"><Search className="mx-auto mb-3 size-7 text-muted-foreground"/><h3 className="font-bold">Тарифы не найдены</h3><p className="mt-1 text-sm text-muted-foreground">Попробуйте изменить страну или тип SIM.</p></div>}
    </section>

    <section id="how" className="bg-[#10213a] py-16 text-white sm:py-20"><div className="mx-auto max-w-[1240px] px-4 sm:px-6"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><p className="mb-3 text-xs font-black uppercase tracking-[.16em] text-[#b7f34a]">Без лишних шагов</p><h2 className="text-3xl font-black tracking-[-.035em] sm:text-4xl">Связь уже ждёт вас в поездке</h2><p className="mt-4 text-sm leading-6 text-[#aebed2]">Для eSIM не нужна доставка: QR-код и инструкция приходят после подтверждения оплаты.</p></div><div className="grid gap-px overflow-hidden rounded-2xl bg-white/10 sm:grid-cols-3">{[{icon:Globe2,n:"01",title:"Выберите страну",text:"Найдите тариф по объёму интернета и сроку."},{icon:CreditCard,n:"02",title:"Оформите заказ",text:"Оплатите криптовалютой или через менеджера."},{icon:Wifi,n:"03",title:"Подключитесь",text:"Установите eSIM по инструкции и выходите в сеть."}].map(s=><div key={s.n} className="bg-[#142944] p-6"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-xl bg-[#b7f34a] text-[#10213a]"><s.icon className="size-5"/></span><span className="font-mono text-xs text-white/35">{s.n}</span></div><h3 className="mt-8 text-lg font-bold">{s.title}</h3><p className="mt-2 text-sm leading-6 text-[#aebed2]">{s.text}</p></div>)}</div></div></div></section>

    <section id="delivery" className="mx-auto max-w-[1240px] px-4 py-16 sm:px-6 sm:py-20"><div className="grid gap-5 md:grid-cols-3"><Feature icon={ShieldCheck} title="Проверенные тарифы" text="Условия активации, срок действия и объём трафика указаны до покупки."/><Feature icon={PackageCheck} title="eSIM сразу на email" text="После подтверждения оплаты вы получите код активации и понятную инструкцию."/><Feature icon={Truck} title="Доставка SIM" text="Физические SIM отправляем с отслеживанием. Срок и стоимость видны в заказе."/></div></section>
    <Faq/>
    <Footer/>
  </main>;
}

function Logo(){return <span className="grid size-10 place-items-center rounded-[13px] bg-[#1168e8] text-white shadow-[0_7px_18px_rgba(17,104,232,.25)]"><Wifi className="size-5"/></span>}
function SearchBox({value,onChange}:{value:string;onChange:(v:string)=>void}){return <div className="relative flex-1"><Search className="absolute left-4 top-1/2 size-5 -translate-y-1/2 text-[#7090b1]"/><Input value={value} onChange={e=>onChange(e.target.value)} className="h-12 border-0 bg-transparent pl-12 text-base shadow-none focus-visible:ring-0" placeholder="Куда вы едете?" aria-label="Поиск по странам и операторам"/></div>}
function Filter({value,onChange,values,narrow=false}:{value:string;onChange:(v:string)=>void;values:string[];narrow?:boolean}){return <Select value={value} onValueChange={onChange}><SelectTrigger className={`h-11 w-full rounded-xl border-[#dbe5ef] bg-white ${narrow?"sm:w-[150px]":"sm:w-[200px]"}`}><SelectValue/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}
function HeroCards(){return <div className="relative mx-auto hidden h-[370px] w-full max-w-[450px] md:block" aria-hidden="true"><MiniSim className="absolute left-4 top-10 rotate-[-8deg] bg-[#10213a] text-white" flag="🇹🇷" country="ТУРЦИЯ" data="20 ГБ" days="30 дней" operator="Turkcell"/><MiniSim className="absolute bottom-4 right-0 rotate-[7deg] bg-[#b7f34a] text-[#10213a]" flag="🇹🇭" country="ТАИЛАНД" data="∞ ГБ" days="15 дней" operator="AIS" light/><span className="absolute right-1 top-2 grid size-20 place-items-center rounded-full bg-white text-center text-[11px] font-black uppercase leading-4 text-[#1168e8] shadow-xl">готово<br/>к поездке</span></div>}
function MiniSim({className,flag,country,data,days,operator,light=false}:{className:string;flag:string;country:string;data:string;days:string;operator:string;light?:boolean}){return <div className={`${className} w-[270px] rounded-[30px] p-5 shadow-2xl`}><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-xl bg-white/10"><Wifi/></span><span className="text-4xl">{flag}</span></div><p className={`mt-14 text-sm ${light?"text-[#10213a]/60":"text-white/60"}`}>{country} · eSIM</p><p className="mt-1 text-3xl font-black">{data}</p><div className={`mt-6 flex justify-between border-t pt-4 text-sm ${light?"border-[#10213a]/15":"border-white/15"}`}><span>{days}</span><span>{operator}</span></div></div>}

function Cart({cart,items,count,total,checkout,ordered,onChange,onCheckout,onOrder}:{cart:Record<number,number>;items:Product[];count:number;total:number;checkout:boolean;ordered:boolean;onChange:(id:number,n:number)=>void;onCheckout:(v:boolean)=>void;onOrder:(v:boolean)=>void}){return <Sheet><SheetTrigger asChild><Button className="relative h-11 rounded-xl bg-[#10213a] px-4 hover:bg-[#1b3456]"><ShoppingBag className="size-[18px]"/><span className="hidden sm:inline">Корзина</span>{count>0&&<span className="absolute -right-2 -top-2 grid size-5 place-items-center rounded-full bg-[#b7f34a] text-[11px] font-black text-[#10213a]">{count}</span>}</Button></SheetTrigger><SheetContent className="w-full border-l-[#dce5f0] bg-white p-0 sm:max-w-[470px]"><SheetHeader className="border-b border-border px-6 py-5"><SheetTitle className="text-xl">Ваша корзина</SheetTitle><SheetDescription>{count?`${count} ${count===1?"товар":"товара"}`:"Пока здесь пусто"}</SheetDescription></SheetHeader>{ordered?<OrderDone/>:checkout?<Checkout total={total} onBack={()=>onCheckout(false)} onOrder={()=>onOrder(true)}/>:items.length?<CartList cart={cart} items={items} total={total} onChange={onChange} onCheckout={()=>onCheckout(true)}/>:<div className="flex flex-1 flex-col items-center justify-center px-8 text-center"><span className="mb-4 grid size-16 place-items-center rounded-full bg-[#edf5ff] text-[#1168e8]"><ShoppingBag className="size-7"/></span><h3 className="text-xl font-bold text-[#10213a]">Выберите подходящую SIM</h3><p className="mt-2 text-sm text-muted-foreground">Добавленные тарифы появятся здесь.</p></div>}</SheetContent></Sheet>}
function OrderDone(){return <div className="flex flex-1 flex-col items-center justify-center px-8 text-center"><span className="mb-5 grid size-16 place-items-center rounded-full bg-[#e8fbd0] text-[#4b8012]"><Check className="size-8"/></span><h3 className="text-2xl font-bold text-[#10213a]">Заказ принят</h3><p className="mt-2 max-w-xs text-sm leading-6 text-muted-foreground">Номер SIM-24091 отправлен на вашу почту. Менеджер свяжется с вами, если потребуется уточнение.</p></div>}
function Checkout({total,onBack,onOrder}:{total:number;onBack:()=>void;onOrder:()=>void}){return <form className="flex flex-1 flex-col overflow-y-auto p-6" onSubmit={e=>{e.preventDefault();onOrder()}}><button type="button" onClick={onBack} className="mb-5 w-fit text-sm font-semibold text-[#1168e8]">← Вернуться в корзину</button><h3 className="mb-5 text-xl font-bold text-[#10213a]">Оформление заказа</h3><div className="space-y-4"><FormField label="Имя" placeholder="Как к вам обращаться"/><FormField label="Email" placeholder="mail@example.com" email/><FormField label="Telegram или телефон" placeholder="@username" optional/><fieldset className="space-y-2"><legend className="mb-2 text-sm font-semibold">Способ оплаты</legend><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-[#1168e8] bg-[#f4f9ff] p-4 text-sm"><input defaultChecked name="payment" type="radio"/>Криптовалюта</label><label className="flex cursor-pointer items-center gap-3 rounded-xl border p-4 text-sm"><input name="payment" type="radio"/>По реквизитам через менеджера</label></fieldset></div><Button type="submit" className="mt-auto h-12 rounded-xl bg-[#1168e8] text-base hover:bg-[#0d56c3]">Создать заказ · {formatPrice(total)}</Button><p className="mt-3 text-center text-xs leading-5 text-muted-foreground">Нажимая кнопку, вы соглашаетесь с условиями использования и политикой конфиденциальности.</p></form>}
function FormField({label,placeholder,email=false,optional=false}:{label:string;placeholder:string;email?:boolean;optional?:boolean}){return <label className="block text-sm font-semibold">{label}<Input required={!optional} type={email?"email":"text"} className="mt-2 h-11 rounded-xl" placeholder={placeholder}/></label>}
function CartList({cart,items,total,onChange,onCheckout}:{cart:Record<number,number>;items:Product[];total:number;onChange:(id:number,n:number)=>void;onCheckout:()=>void}){return <div className="flex flex-1 flex-col overflow-hidden"><div className="flex-1 space-y-3 overflow-y-auto p-6">{items.map(i=><div key={i.id} className="flex gap-4 rounded-2xl border border-border bg-[#f9fbfd] p-4"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-white text-2xl shadow-sm">{i.flag}</span><div className="min-w-0 flex-1"><p className="font-bold text-[#10213a]">{i.country} · {i.data}</p><p className="mt-1 text-xs text-muted-foreground">{i.type} · {i.days} дней</p><div className="mt-3 flex items-center gap-2"><Qty onClick={()=>onChange(i.id,-1)}><Minus/></Qty><span className="w-5 text-center text-sm font-bold">{cart[i.id]}</span><Qty onClick={()=>onChange(i.id,1)}><Plus/></Qty></div></div><div className="text-right"><p className="font-bold">{formatPrice(i.price*cart[i.id])}</p><button onClick={()=>onChange(i.id,-cart[i.id])} aria-label={`Удалить ${i.country}`} className="mt-4 text-muted-foreground hover:text-red-500"><Trash2 className="size-4"/></button></div></div>)}</div><div className="border-t bg-white p-6"><div className="mb-4 flex justify-between text-lg font-bold"><span>Итого</span><span>{formatPrice(total)}</span></div><Button onClick={onCheckout} className="h-12 w-full rounded-xl bg-[#1168e8] text-base hover:bg-[#0d56c3]">Перейти к оформлению<ArrowRight/></Button><div className="mt-4 flex items-center justify-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="size-4 text-[#439313]"/>Цена и наличие проверяются перед оплатой</div></div></div>}
function Qty({onClick,children}:{onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className="grid size-7 place-items-center rounded-lg border bg-white [&_svg]:size-3">{children}</button>}

function ProductCard({product,count,onAdd}:{product:Product;count:number;onAdd:()=>void}){return <article className="group overflow-hidden rounded-[22px] border border-[#dce5ee] bg-white transition duration-300 hover:-translate-y-1 hover:shadow-[0_18px_45px_rgba(23,58,96,.12)]"><div className={`relative h-[128px] bg-gradient-to-br ${product.tone} p-5 text-white`}><div className="flex items-start justify-between"><span className="rounded-lg bg-white/15 px-2.5 py-1 text-[11px] font-black uppercase tracking-wider backdrop-blur">{product.type}</span><span className="text-3xl drop-shadow">{product.flag}</span></div>{product.popular&&<span className="absolute bottom-4 left-5 flex items-center gap-1 rounded-full bg-[#b7f34a] px-2.5 py-1 text-[10px] font-black uppercase tracking-wide text-[#10213a]"><Star className="size-3 fill-current"/>Хит продаж</span>}<span className="absolute bottom-4 right-5 text-xs font-semibold text-white/70">{product.operator}</span></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-[#7a899a]">{product.region}</p><h3 className="mt-1 text-xl font-black tracking-tight text-[#10213a]">{product.country}</h3></div><div className="text-right"><p className="text-xl font-black text-[#10213a]">{formatPrice(product.price)}</p>{product.oldPrice&&<p className="text-xs text-muted-foreground line-through">{formatPrice(product.oldPrice)}</p>}</div></div><div className="mt-5 grid grid-cols-2 gap-2"><Spec icon={Wifi} label="Интернет" value={product.data}/><Spec icon={Clock3} label="Срок" value={`${product.days} дней`}/>{product.calls&&<Spec icon={Smartphone} label="Звонки" value={product.calls}/>}<Spec icon={Globe2} label="Активация" value="По прибытии"/></div><Button onClick={onAdd} className="mt-5 h-11 w-full rounded-xl bg-[#10213a] font-bold hover:bg-[#1168e8]">{count?<><Check className="size-4"/>В корзине · {count}</>:<>Добавить в корзину<Plus className="size-4"/></>}</Button></div></article>}
function Spec({icon:Icon,label,value}:{icon:typeof Wifi;label:string;value:string}){return <div className="rounded-xl bg-[#f5f8fb] p-3"><div className="flex items-center gap-1.5 text-[11px] text-[#7a899a]"><Icon className="size-3.5"/>{label}</div><p className="mt-1 text-sm font-bold text-[#283b54]">{value}</p></div>}
function Feature({icon:Icon,title,text}:{icon:typeof Wifi;title:string;text:string}){return <div className="rounded-2xl border border-[#dbe5ef] p-6"><span className="grid size-11 place-items-center rounded-xl bg-[#e9f3ff] text-[#1168e8]"><Icon className="size-5"/></span><h3 className="mt-5 text-lg font-bold text-[#10213a]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#637389]">{text}</p></div>}
function Faq(){const items=[{q:"Как проверить, поддерживает ли телефон eSIM?",a:"В настройках устройства найдите пункт «Добавить eSIM» или «Добавить сотовый тариф». Перед покупкой также проверьте модель в списке совместимых устройств."},{q:"Когда начинается срок действия тарифа?",a:"Условия зависят от оператора: чаще всего срок начинается при первом подключении к сети в стране назначения. Точное правило указано в карточке тарифа."},{q:"Можно ли раздать интернет?",a:"Для большинства тарифов режим модема доступен. Если оператор вводит ограничения, мы указываем это в условиях конкретного предложения."}];return <section id="faq" className="border-y border-[#dce7f4] bg-[#f7fbff] py-16 sm:py-20"><div className="mx-auto grid max-w-[1000px] gap-8 px-4 sm:px-6 md:grid-cols-[.75fr_1.25fr]"><div><CircleHelp className="mb-4 size-8 text-[#1168e8]"/><h2 className="text-3xl font-black tracking-[-.035em] text-[#10213a]">Частые вопросы</h2><p className="mt-3 text-sm leading-6 text-[#637389]">Не нашли ответ? Напишите в поддержку — поможем проверить совместимость и выбрать тариф.</p></div><div className="space-y-3">{items.map((i,n)=><details key={i.q} open={n===0} className="group rounded-2xl border border-[#dbe5ef] bg-white p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-bold text-[#10213a]">{i.q}<ChevronDown className="size-5 shrink-0 transition-transform group-open:rotate-180"/></summary><p className="mt-3 pr-8 text-sm leading-6 text-[#637389]">{i.a}</p></details>)}</div></div></section>}
function Footer(){return <footer className="bg-white"><div className="mx-auto max-w-[1240px] px-4 py-12 sm:px-6"><div className="grid gap-10 border-b border-border pb-10 md:grid-cols-[1.5fr_1fr_1fr_1fr]"><div><div className="flex items-center gap-2.5"><Logo/><span className="text-xl font-black tracking-[-.04em] text-[#10213a]">SIMKA</span></div><p className="mt-4 max-w-xs text-sm leading-6 text-[#637389]">SIM и eSIM для путешествий. Оставайтесь на связи без дорогого роуминга.</p></div><FooterColumn title="Покупателям" links={["Каталог","Оплата","Доставка","Возврат"]}/><FooterColumn title="О компании" links={["О нас","Контакты","Поддержка","Партнёрам"]}/><FooterColumn title="Документы" links={["Конфиденциальность","Условия","Cookie"]}/></div><div className="flex flex-col gap-3 pt-6 text-xs text-[#7a899a] sm:flex-row sm:items-center sm:justify-between"><span>© 2026 SIMKA. Все права защищены.</span><span>Цены указаны в российских рублях</span></div></div></footer>}
function FooterColumn({title,links}:{title:string;links:string[]}){return <div><h3 className="text-sm font-bold text-[#10213a]">{title}</h3><ul className="mt-4 space-y-3 text-sm text-[#637389]">{links.map(l=><li key={l}><a href="#" className="hover:text-[#1168e8]">{l}</a></li>)}</ul></div>}
function formatPrice(value:number){return `${new Intl.NumberFormat("ru-RU").format(value)} ₽`}
