/* eslint-disable @next/next/no-html-link-for-pages -- full page navigation keeps static hosting and Render routes reliable. */
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({ title: "Регистрация — SIMKA", description: "Создайте личный кабинет SIMKA.", path: "/account/register", noindex: true });

export default async function RegisterPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams;
  const error = typeof params.error === "string" ? params.error : "";
  return <main className="min-h-screen bg-[#f7fbff] px-4 py-10 text-[#10213a]"><div className="mx-auto max-w-md"><a href="/" className="text-sm font-bold text-[#1168e8]">← На главную</a><section className="mt-8 rounded-2xl border border-[#dbe5ef] bg-white p-6 shadow-[0_12px_35px_rgba(23,58,96,.06)]"><p className="text-xs font-black uppercase tracking-[.16em] text-[#1168e8]">SIMKA</p><h1 className="mt-2 text-3xl font-black">Создать кабинет</h1><p className="mt-2 text-sm text-[#637389]">После регистрации заказы с этим email будут доступны в истории.</p>{error&&<p role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}<form action="/api/account/register" method="post" className="mt-6 space-y-4"><label className="block text-sm font-semibold">Имя<input name="name" required minLength={2} maxLength={100} autoComplete="name" className="mt-2 h-11 w-full rounded-xl border border-[#cddbea] px-3 font-normal outline-none focus:ring-2 focus:ring-[#1168e8]"/></label><label className="block text-sm font-semibold">Email<input name="email" type="email" required maxLength={254} autoComplete="email" className="mt-2 h-11 w-full rounded-xl border border-[#cddbea] px-3 font-normal outline-none focus:ring-2 focus:ring-[#1168e8]"/></label><label className="block text-sm font-semibold">Telegram или телефон<span className="font-normal text-[#7a899a]"> — необязательно</span><input name="contact" maxLength={100} autoComplete="tel" className="mt-2 h-11 w-full rounded-xl border border-[#cddbea] px-3 font-normal outline-none focus:ring-2 focus:ring-[#1168e8]" placeholder="@username или +7…"/></label><label className="block text-sm font-semibold">Пароль <span className="font-normal text-[#7a899a]">— минимум 12 символов</span><input name="password" type="password" required minLength={12} maxLength={200} autoComplete="new-password" className="mt-2 h-11 w-full rounded-xl border border-[#cddbea] px-3 font-normal outline-none focus:ring-2 focus:ring-[#1168e8]"/></label><label className="block text-sm font-semibold">Повторите пароль<input name="passwordConfirmation" type="password" required minLength={12} maxLength={200} autoComplete="new-password" className="mt-2 h-11 w-full rounded-xl border border-[#cddbea] px-3 font-normal outline-none focus:ring-2 focus:ring-[#1168e8]"/></label><button className="min-h-11 w-full rounded-xl bg-[#1168e8] px-4 font-bold text-white hover:bg-[#0d56c3]">Зарегистрироваться</button></form><p className="mt-5 text-center text-sm text-[#637389]">Уже есть аккаунт? <a href="/account/login" className="font-bold text-[#1168e8]">Войти</a></p></section></div></main>;
}
